### ISSUE TITLE
error message (when running on http://doc-test.dart-services.appspot.com/)

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-services#120]
This is the code I used (offset 80):
```dart
void main() {
  for (int i = 0; i < 4; i++) {
    print('hello ${i}');
    int j
  }
}
```
If I run this locally (latest master), then everything goes fine, but I use http://doc-test.dart-services.appspot.com/ then I get the following error message (at apitest.html)

```
500 Internal Server Error - 332ms
pragma: no-cache
content-type: application/json; charset=utf-8
cache-control: no-cache, no-store, must-revalidate
expires: 0

{"error":{"code":500,"message":"UnimplementedError: Server responded with an error: {\"error\":{\"code\":\"SERVER_ERROR\",\"message\":\"Class 'ExpressionStatement' has no instance getter 'name'.\\n\\nNoSuchMethodError: method not found: 'name'\\nReceiver: Instance of 'ExpressionStatement'\\nArguments: []\",\"stackTrace\":\"#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)\\n#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)\\n#2      FixProcessor._addFix_createField (package:analysis_server/src/services/correction/fix_internal.dart:610:28)\\n#3      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:207:28)\\n#4      computeFixes (package:analysis_server/src/services/correction/fix.dart:20:38)\\n#5      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:144:43)\\n#6      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:174:24)\\n#7      handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:597:58)\\n#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:150:15)\\n#9      handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:593:66)\\n#10     _rootRun (dart:async/zone.dart:895)\\n#11     _CustomZone.run (dart:async/zone.dart:796)\\n#12     _CustomZone.runGuarded (dart:async/zone.dart:704)\\n#13     runZoned (dart:async/zone.dart:1249)\\n#14     handleRequest (package:analysis_server/src/analysis_server.dart:592:13)\\n#15     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170:16)\\n#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:150:15)\\n#17     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:63)\\n#18     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109:46)\\n#19     _rootRunUnary (dart:async/zone.dart:902)\\n#20     _CustomZone.runUnary (dart:async/zone.dart:804)\\n#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)\\n#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)\\n#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)\\n#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)\\n#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)\\n#26     add (dart:convert/string_conversion.dart:256)\\n#27     _LineSplitterSink._addSlice (dart:convert/line_splitter.dart:76)\\n#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:48)\\n#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)\\n#30     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:89)\\n#31     _handleData (dart:async/stream_transformers.dart:119)\\n#32     _rootRunUnary (dart:async/zone.dart:902)\\n#33     _CustomZone.runUnary (dart:async/zone.dart:804)\\n#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)\\n#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)\\n#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)\\n#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)\\n#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)\\n#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)\\n#40     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)\\n#41     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)\\n#42     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)\\n#43     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:89)\\n#44     _handleData (dart:async/stream_transformers.dart:119)\\n#45     _rootRunUnary (dart:async/zone.dart:902)\\n#46     _CustomZone.runUnary (dart:async/zone.dart:804)\\n#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)\\n#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)\\n#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)\\n#50     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)\\n#51     _StreamController._add (dart:async/stream_controller.dart:570)\\n#52     _StreamController.add (dart:async/stream_controller.dart:516)\\n#53     _onData (dart:io-patch/socket_patch.dart:1764)\\n#54     _rootRunUnary (dart:async/zone.dart:906)\\n#55     _CustomZone.runUnary (dart:async/zone.dart:804)\\n#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)\\n#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)\\n#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)\\n#59     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)\\n#60     _StreamController._add (dart:async/stream_controller.dart:570)\\n#61     _StreamController.add (dart:async/stream_controller.dart:516)\\n#62     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1331)\\n#63     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:715)\\n#64     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)\\n#65     _asyncRunCallback (dart:async/schedule_microtask.dart:48)\\n#66     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)\\n#67     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)\\n\"},\"id\":\"691\"}"}}
```

**Comment by lukechurch** [comment]
If I run this through local server I get 

`
500 Internal Server Error - 9391ms
pragma: no-cache
content-type: application/json; charset=utf-8
cache-control: no-cache, no-store, must-revalidate
expires: 0

{"error":{"code":500,"message":"Unknown API Error."}}`

So the error is the same, it's just that it doesn't pass the detail.

**Comment by lukechurch** [comment]
The error is expected until: https://code.google.com/p/dart/issues/detail?id=23103 gets fixed

**Comment by kasperpeulen** [comment]
I get this message:
```
200 OK - 4776ms
pragma: no-cache
content-type: application/json; charset=utf-8
cache-control: no-cache, no-store, must-revalidate
expires: 0

{
 "fixes": [
  {
   "fixes": [
    {
     "message": "Insert ';'",
     "edits": [
      {
       "offset": 84,
       "length": 0,
       "replacement": ";"
      }
     ]
    }
   ],
   "problemMessage": "Expected to find ';'",
   "offset": 83,
   "length": 1
  },
  {
   "fixes": [
    {
     "message": "Insert ';'",
     "edits": [
      {
       "offset": 82,
       "length": 0,
       "replacement": ";"
      }
     ]
    }
   ],
   "problemMessage": "Expected to find ';'",
   "offset": 79,
   "length": 3
  }
 ]
}
```

**Comment by lukechurch** [comment]
I can make this happen, but only if i change the code slightly. 

Try:

void main() { int i }

Select offset 19, just after the i. response:

```
500 Internal Server Error - 8960ms
pragma: no-cache
content-type: application/json; charset=utf-8
cache-control: no-cache, no-store, must-revalidate
expires: 0

{"error":{"code":500,"message":"Unknown API Error."}}
```

In the dev console you'll see:

```
Observatory listening on http://127.0.0.1:60829
[INFO] rpc: Adding /dartservices/v1 to set of valid APIs.
[INFO] services: Listening on port 8080
2015-04-05 17:45:21.091	0:00:00.003408	OPTIONS	[200]	/api/dartservices/v1/fixes
[INFO] rpc: Adding /discovery/v1 to set of valid APIs.
[INFO] rpc: Enabling Discovery API Service for server: http://localhost:8080
[INFO] rpc: Invoking API: /dartservices/v1 with HTTP method: POST on path: /dartservices/v1/fixes.
[FINER] rpc: 
Request for API /dartservices/v1:
  Method: POST
  Path: /dartservices/v1/fixes
    accept: */*
    accept-encoding: gzip, deflate
    accept-language: en-US,en;q=0.8
    connection: keep-alive
    content-length: 46
    content-type: application/json; charset=UTF-8
    host: localhost:8080
    origin: http://localhost:8081
    referer: http://localhost:8081/apitest.html
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.0 (Dart) Safari/537.36
  Body:
    {source: void main() { int i }, offset: 19}

[FINE] rpc: 
Invoking method: fix with:
  Positional Parameters:
    Instance of 'SourceRequest'
  Named Parameters:

[FINE] services: FIX, 19, void main() { int i }
[FINE] analysis_server: ensureSetup: SETUP false IS_SETTING_UP false
[FINE] analysis_server: Setup starting
[FINE] analysis_server: Server about to start
[FINE] analysis_server: Binary: /Users/lukechurch/Downloads/dart1-10/dart-sdk/bin/dart
[FINE] analysis_server: Arguments: [bin/_analysis_server_entry.dart, --sdk, /Users/lukechurch/Downloads/dart1-10/dart-sdk]
[FINE] analysis_server: io.Process.then returned
[FINE] analysis_server: Setver started
[FINE] analysis_server: Server.send server.setSubscriptions
[FINE] analysis_server: SEND: {"id":"0","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
[FINE] analysis_server: Server Set Subscriptions completed
[FINE] analysis_server: About to send analysis.updateContent
[FINE] analysis_server: Server.send analysis.updateContent
[FINE] analysis_server: SEND: {"id":"1","method":"analysis.updateContent","params":{"files":{"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart":{"type":"add","content":"main() { int b = 2;  b++;   b. }"}}}}
[FINE] analysis_server: RECV: {"event":"server.connected","params":{"version":"1.3.0"}}
[FINE] analysis_server: RECV: {"id":"0"}
[FINE] analysis_server: RECV: {"id":"1","result":{}}
[FINE] analysis_server: analysis.updateContent -> then
[FINE] analysis_server: Server.send analysis.setAnalysisRoots
[FINE] analysis_server: SEND: {"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi"],"excluded":[]}}
[FINE] analysis_server: Server.send analysis.setPriorityFiles
[FINE] analysis_server: SEND: {"id":"3","method":"analysis.setPriorityFiles","params":{"files":["/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart"]}}
[FINE] analysis_server: Setup done
[FINE] analysis_server: RECV: {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
[FINE] analysis_server: RECV: {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
[FINE] analysis_server: RECV: {"id":"2"}
[FINE] analysis_server: RECV: {"id":"3"}
[FINE] analysis_server: RECV: {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[FINE] analysis_server: RECV: {"event":"analysis.errors","params":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","errors":[]}}
[FINE] analysis_server: RECV: {"event":"analysis.errors","params":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":31,"length":1,"startLine":1,"startColumn":32},"message":"Expected an identifier"},{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":31,"length":1,"startLine":1,"startColumn":32},"message":"Expected to find ';'"}]}}
[FINE] analysis_server: RECV: {"event":"analysis.errors","params":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":31,"length":1,"startLine":1,"startColumn":32},"message":"Expected an identifier"},{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":31,"length":1,"startLine":1,"startColumn":32},"message":"Expected to find ';'"},{"severity":"WARNING","type":"STATIC_TYPE_WARNING","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":31,"length":0,"startLine":1,"startColumn":32},"message":"The getter '' is not defined for the class 'int'"}]}}
[FINE] analysis_server: RECV: {"event":"analysis.errors","params":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":31,"length":1,"startLine":1,"startColumn":32},"message":"Expected an identifier"},{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":31,"length":1,"startLine":1,"startColumn":32},"message":"Expected to find ';'"},{"severity":"WARNING","type":"STATIC_TYPE_WARNING","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":31,"length":0,"startLine":1,"startColumn":32},"message":"The getter '' is not defined for the class 'int'"}]}}
[FINE] analysis_server: RECV: {"event":"analysis.errors","params":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":31,"length":1,"startLine":1,"startColumn":32},"message":"Expected an identifier"},{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":31,"length":1,"startLine":1,"startColumn":32},"message":"Expected to find ';'"},{"severity":"WARNING","type":"STATIC_TYPE_WARNING","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":31,"length":0,"startLine":1,"startColumn":32},"message":"The getter '' is not defined for the class 'int'"}]}}
[FINE] analysis_server: RECV: {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[FINE] analysis_server: About to send analysis.updateContent
[FINE] analysis_server: Server.send analysis.updateContent
[FINE] analysis_server: SEND: {"id":"4","method":"analysis.updateContent","params":{"files":{"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart":{"type":"add","content":"void main() { int i }"}}}}
[FINE] analysis_server: Server.send edit.getFixes
[FINE] analysis_server: SEND: {"id":"5","method":"edit.getFixes","params":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":19}}
[FINE] analysis_server: RECV: {"id":"4","result":{}}
[FINE] analysis_server: analysis.updateContent -> then
[FINE] analysis_server: RECV: {"error":{"code":"SERVER_ERROR","message":"Class 'ExpressionStatement' has no instance getter 'name'.\n\nNoSuchMethodError: method not found: 'name'\nReceiver: Instance of 'ExpressionStatement'\nArguments: []","stackTrace":"#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)\n#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)\n#2      FixProcessor._addFix_createField (package:analysis_server/src/services/correction/fix_internal.dart:610:28)\n#3      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:207:9)\n#4      computeFixes (package:analysis_server/src/services/correction/fix.dart:20:31)\n#5      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:144:31)\n#6      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:174:16)\n#7      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:597:45)\n#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:150:15)\n#9      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:593:50)\n#10     _rootRun (dart:async/zone.dart:895)\n#11     _CustomZone.run (dart:async/zone.dart:796)\n#12     _CustomZone.runGuarded (dart:async/zone.dart:704)\n#13     runZoned (dart:async/zone.dart:1249)\n#14     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:592:5)\n#15     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170:16)\n#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:150:15)\n#17     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)\n#18     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109:34)\n#19     _rootRunUnary (dart:async/zone.dart:902)\n#20     _CustomZone.runUnary (dart:async/zone.dart:804)\n#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)\n#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)\n#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)\n#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)\n#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)\n#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)\n#27     _LineSplitterSink._addSlice (dart:convert/line_splitter.dart:76)\n#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:48)\n#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)\n#30     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:89)\n#31     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)\n#32     _rootRunUnary (dart:async/zone.dart:902)\n#33     _CustomZone.runUnary (dart:async/zone.dart:804)\n#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)\n#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)\n#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)\n#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)\n#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)\n#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)\n#40     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)\n#41     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)\n#42     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)\n#43     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:89)\n#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)\n#45     _rootRunUnary (dart:async/zone.dart:902)\n#46     _CustomZone.runUnary (dart:async/zone.dart:804)\n#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)\n#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)\n#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)\n#50     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)\n#51     _StreamController._add (dart:async/stream_controller.dart:570)\n#52     _StreamController.add (dart:async/stream_controller.dart:516)\n#53     _Socket._onData (dart:io-patch/socket_patch.dart:1793)\n#54     _rootRunUnary (dart:async/zone.dart:906)\n#55     _CustomZone.runUnary (dart:async/zone.dart:804)\n#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)\n#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)\n#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)\n#59     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)\n#60     _StreamController._add (dart:async/stream_controller.dart:570)\n#61     _StreamController.add (dart:async/stream_controller.dart:516)\n#62     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1344)\n#63     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:728)\n#64     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)\n#65     _asyncRunCallback (dart:async/schedule_microtask.dart:48)\n#66     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)\n#67     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)\n"},"id":"5"}
[WARNING] rpc: 
Response
  Status Code: 500
  Headers:
    cache-control: no-cache, no-store, must-revalidate
    content-type: application/json; charset=utf-8
    expires: 0
    pragma: no-cache
  Exception:
    Exception: type 'UnimplementedError' is not a subtype of type 'Exception' of 'e'.

2015-04-05 17:45:21.143	0:00:08.855773	POST	[500]	/api/dartservices/v1/fixes
[FINE] analysis_server: RECV: {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[FINE] analysis_server: RECV: {"event":"analysis.errors","params":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":18,"length":1,"startLine":1,"startColumn":19},"message":"Expected to find ';'"},{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":14,"length":3,"startLine":1,"startColumn":15},"message":"Expected to find ';'"},{"severity":"WARNING","type":"STATIC_WARNING","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":18,"length":1,"startLine":1,"startColumn":19},"message":"Undefined name 'i'"}]}}
[FINE] analysis_server: RECV: {"event":"analysis.errors","params":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":18,"length":1,"startLine":1,"startColumn":19},"message":"Expected to find ';'"},{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":14,"length":3,"startLine":1,"startColumn":15},"message":"Expected to find ';'"},{"severity":"WARNING","type":"STATIC_WARNING","location":{"file":"/var/folders/00/0v318000h01000cxqpysvccm003cc5/T/analysisServerELNUAi/main.dart","offset":18,"length":1,"startLine":1,"startColumn":19},"message":"Undefined name 'i'"}]}}
[FINE] analysis_server: RECV: {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
```

**Comment by lukechurch** [comment]
(This is on HEAD of master)

**Comment by lukechurch** [comment]
If you don't see this, please paste the dump from the dev console of the server here, so I can look at what it's doing :)

**Comment by lukechurch** [comment]
I'm pushing a new doc-test version just in case they have got out of sync somehow.
